// <auto-generated />
using System;
using EventSourcing.Abstractions.Contracts;

namespace EventSourcing.Abstractions.Identities
{
    /// <summary>
    /// Command sequence identifier.
    /// </summary>
    /// <remarks>Generated from EventSourcing.CodeGeneration.Identities.tt</remarks>
    public readonly struct CommandSequenceId : IIdentity, IEquatable<CommandSequenceId>
    {
        private readonly Guid _id;

        /// <summary>
        /// Get the prefix.
        /// </summary>
        public static readonly string Prefix = "command-sequence_";

        /// <summary>
        /// Get empty CommandSequenceId.
        /// </summary>
        public static readonly CommandSequenceId Empty = new CommandSequenceId(Guid.Empty);

        /// <summary>
        /// Create CommandSequenceId with random value.
        /// </summary>
        public static CommandSequenceId New()
        {
            return new CommandSequenceId(Guid.NewGuid());
        }

        /// <summary>
        /// Initiate new object.
        /// </summary>
        public CommandSequenceId(Guid id)
        {
            _id = id;
        }

        /// <summary>
        /// Parse from string.
        /// </summary>
        /// <param name="serializedId">String value.</param>
        /// <returns>Command sequence identifier.</returns>
        /// <exception cref="ArgumentException">String cannot be parsed to CommandSequenceId.</exception>
        public static CommandSequenceId Parse(string serializedId)
        {
            if (!serializedId.StartsWith(Prefix, StringComparison.Ordinal))
            {
                throw new ArgumentException("Invalid CommandSequenceId", "serializedId");
            }

            ReadOnlySpan<char> span = serializedId.AsSpan();
            Guid id = Guid.Parse(span.Slice(Prefix.Length));

            return new CommandSequenceId(id);
        }

        /// <summary>
        /// Parse from string without throwing exception.
        /// </summary>
        /// <param name="serializedId">String value.</param>
        /// <param name="id">Parsed CommandSequenceId.</param>
        /// <returns>True if parsed successfully, otherwise false.</returns>
        public static bool TryParse(string serializedId, out CommandSequenceId id)
        {
            Guid guid;

            if (!string.IsNullOrWhiteSpace(serializedId) && serializedId.StartsWith(Prefix, StringComparison.Ordinal))
            {
                ReadOnlySpan<char> span = serializedId.AsSpan().Slice(Prefix.Length);
                if (Guid.TryParse(span, out guid))
                {
                    id = new CommandSequenceId(guid);
                    return true;
                }
            }

            id = default(CommandSequenceId);
            return false;
        }

        /// <summary>
        /// Get internal id.
        /// </summary>
        public Guid Id => _id;

        public static implicit operator Guid(CommandSequenceId id)
        {
            return id._id;
        }

        public static implicit operator CommandSequenceId(Guid id)
        {
            return new CommandSequenceId(id);
        }

        public override string ToString()
        {
            return string.Concat(Prefix, _id.ToString());
        }

        public bool Equals(CommandSequenceId other) { return _id == other._id; }

        public override bool Equals(object other)
        {
            if ((other == null) || !(other is CommandSequenceId)) 
            {
                return false;
            }

            return this.Equals((CommandSequenceId)other);
        }

        public override int GetHashCode() { return _id.GetHashCode(); }

        public static bool operator ==(CommandSequenceId a, CommandSequenceId b) { return a._id == b._id; }
        public static bool operator !=(CommandSequenceId a, CommandSequenceId b) { return a._id != b._id; }
    }
}

