// <auto-generated />
using System;
using EventSourcing.Net.Abstractions.Contracts;

namespace EventSourcing.Net.Abstractions.Identities
{
    /// <summary>
    /// Command identifier.
    /// </summary>
    /// <remarks>Generated from EventSourcing.Net.CodeGeneration.Identities.tt</remarks>
    public readonly struct CommandId : IIdentity, IEquatable<CommandId>, IFormattable, ISpanFormattable
    {
        private readonly Guid _id;

        /// <summary>
        /// Get the prefix.
        /// </summary>
        public static readonly string Prefix = "command_";

        /// <summary>
        /// Get empty CommandId.
        /// </summary>
        public static readonly CommandId Empty = new CommandId(Guid.Empty);

        /// <summary>
        /// Create CommandId with random value.
        /// </summary>
        public static CommandId New()
        {
            return new CommandId(Guid.NewGuid());
        }

        /// <summary>
        /// Initiate new object.
        /// </summary>
        public CommandId(Guid id)
        {
            _id = id;
        }

        /// <summary>
        /// Parse from string.
        /// </summary>
        /// <param name="serializedId">Value to parse.</param>
        /// <returns>Command identifier.</returns>
        /// <exception cref="ArgumentException">String cannot be parsed to CommandId.</exception>
        public static CommandId Parse(ReadOnlySpan<char> serializedId)
        {
            if (!serializedId.StartsWith(Prefix, StringComparison.Ordinal))
            {
                Thrown.ArgumentException("CommandId shouldn't be null and should starts with prefix " + Prefix, nameof(serializedId));
            }
            
            Guid id = Guid.Parse(serializedId.Slice(Prefix.Length));

            return new CommandId(id);
        }

        /// <summary>
        /// Parse from string.
        /// </summary>
        /// <param name="serializedId">String value.</param>
        /// <returns>Command identifier.</returns>
        /// <exception cref="ArgumentException">String cannot be parsed to CommandId.</exception>
        public static CommandId Parse(string serializedId)
        {
            if (serializedId == null)
            {
                Thrown.ArgumentNullException(nameof(serializedId));
            }

            return Parse(serializedId.AsSpan());
        }

        /// <summary>
        /// Parse from string without throwing exception.
        /// </summary>
        /// <param name="serializedId">Value to parse.</param>
        /// <param name="id">Parsed CommandId.</param>
        /// <returns>True if parsed successfully, otherwise false.</returns>
        public static bool TryParse(ReadOnlySpan<char> serializedId, out CommandId id)
        {
            Guid guid;

            if (serializedId.StartsWith(Prefix, StringComparison.Ordinal))
            {
                ReadOnlySpan<char> span = serializedId.Slice(Prefix.Length);
                if (Guid.TryParse(span, out guid))
                {
                    id = new CommandId(guid);
                    return true;
                }
            }

            id = default(CommandId);
            return false;
        }


        /// <summary>
        /// Parse from string without throwing exception.
        /// </summary>
        /// <param name="serializedId">String value.</param>
        /// <param name="id">Parsed CommandId.</param>
        /// <returns>True if parsed successfully, otherwise false.</returns>
        public static bool TryParse(string serializedId, out CommandId id)
        {
            if (serializedId == null)
            {
                id = default;
                return false;
            }

            return TryParse(serializedId.AsSpan(), out id);
        }

        /// <summary>
        /// Get internal id.
        /// </summary>
        public Guid Id => _id;

        public static implicit operator Guid(CommandId id)
        {
            return id._id;
        }

        public static implicit operator CommandId(Guid id)
        {
            return new CommandId(id);
        }

        public override string ToString()
        {
            return string.Concat(Prefix, _id.ToString());
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return string.Concat(Prefix, _id.ToString(format, formatProvider));
        }

        public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider provider)
        {
            int prefixLength = Prefix.Length;
            Span<char> buffer = stackalloc char[prefixLength + 68];
            Span<char> prefixBuffer = buffer.Slice(0, prefixLength);
            Span<char> idBuffer = buffer.Slice(prefixLength);
            
            ReadOnlySpan<char> prefixSpan = Prefix.AsSpan();
            charsWritten = 0;
            if (!Prefix.TryCopyTo(prefixBuffer))
            {
                return false;
            }

            charsWritten = Prefix.Length;
            if (!_id.TryFormat(idBuffer, out int idWritten, format))
            {
                return false;
            }

            charsWritten += idWritten;
            buffer = buffer.Slice(0, charsWritten);
            
            return buffer.TryCopyTo(destination);
        }

        public bool Equals(CommandId other) { return _id == other._id; }

        public override bool Equals(object other)
        {
            if ((other == null) || !(other is CommandId)) 
            {
                return false;
            }

            return this.Equals((CommandId)other);
        }

        public override int GetHashCode() { return _id.GetHashCode(); }

        public static bool operator ==(CommandId a, CommandId b) { return a._id == b._id; }
        public static bool operator !=(CommandId a, CommandId b) { return a._id != b._id; }
    }
}
