// <auto-generated />
using System;
using EventSourcing.Net.Abstractions.Contracts;

namespace EventSourcing.Net.Abstractions.Identities
{
    /// <summary>
    /// Command sequence identifier.
    /// </summary>
    /// <remarks>Generated from EventSourcing.Net.CodeGeneration.Identities.tt</remarks>
    public readonly struct CommandSequenceId : IIdentity, IEquatable<CommandSequenceId>, IFormattable, ISpanFormattable
    {
        private readonly Guid _id;

        /// <summary>
        /// Get the prefix.
        /// </summary>
        public static readonly string Prefix = "command-sequence_";

        /// <summary>
        /// Get empty CommandSequenceId.
        /// </summary>
        public static readonly CommandSequenceId Empty = new CommandSequenceId(Guid.Empty);

        /// <summary>
        /// Create CommandSequenceId with random value.
        /// </summary>
        public static CommandSequenceId New()
        {
            return new CommandSequenceId(Guid.NewGuid());
        }

        /// <summary>
        /// Initiate new object.
        /// </summary>
        public CommandSequenceId(Guid id)
        {
            _id = id;
        }

        /// <summary>
        /// Parse from string.
        /// </summary>
        /// <param name="serializedId">Value to parse.</param>
        /// <returns>Command sequence identifier.</returns>
        /// <exception cref="ArgumentException">String cannot be parsed to CommandSequenceId.</exception>
        public static CommandSequenceId Parse(ReadOnlySpan<char> serializedId)
        {
            if (!serializedId.StartsWith(Prefix, StringComparison.Ordinal))
            {
                Thrown.ArgumentException("CommandSequenceId shouldn't be null and should starts with prefix " + Prefix, nameof(serializedId));
            }
            
            Guid id = Guid.Parse(serializedId.Slice(Prefix.Length));

            return new CommandSequenceId(id);
        }

        /// <summary>
        /// Parse from string.
        /// </summary>
        /// <param name="serializedId">String value.</param>
        /// <returns>Command sequence identifier.</returns>
        /// <exception cref="ArgumentException">String cannot be parsed to CommandSequenceId.</exception>
        public static CommandSequenceId Parse(string serializedId)
        {
            if (serializedId == null)
            {
                Thrown.ArgumentNullException(nameof(serializedId));
            }

            return Parse(serializedId.AsSpan());
        }

        /// <summary>
        /// Parse from string without throwing exception.
        /// </summary>
        /// <param name="serializedId">Value to parse.</param>
        /// <param name="id">Parsed CommandSequenceId.</param>
        /// <returns>True if parsed successfully, otherwise false.</returns>
        public static bool TryParse(ReadOnlySpan<char> serializedId, out CommandSequenceId id)
        {
            Guid guid;

            if (serializedId.StartsWith(Prefix, StringComparison.Ordinal))
            {
                ReadOnlySpan<char> span = serializedId.Slice(Prefix.Length);
                if (Guid.TryParse(span, out guid))
                {
                    id = new CommandSequenceId(guid);
                    return true;
                }
            }

            id = default(CommandSequenceId);
            return false;
        }


        /// <summary>
        /// Parse from string without throwing exception.
        /// </summary>
        /// <param name="serializedId">String value.</param>
        /// <param name="id">Parsed CommandSequenceId.</param>
        /// <returns>True if parsed successfully, otherwise false.</returns>
        public static bool TryParse(string serializedId, out CommandSequenceId id)
        {
            if (serializedId == null)
            {
                id = default;
                return false;
            }

            return TryParse(serializedId.AsSpan(), out id);
        }

        /// <summary>
        /// Get internal id.
        /// </summary>
        public Guid Id => _id;

        public static implicit operator Guid(CommandSequenceId id)
        {
            return id._id;
        }

        public static implicit operator CommandSequenceId(Guid id)
        {
            return new CommandSequenceId(id);
        }

        public override string ToString()
        {
            return string.Concat(Prefix, _id.ToString());
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return string.Concat(Prefix, _id.ToString(format, formatProvider));
        }

        public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider provider)
        {
            int prefixLength = Prefix.Length;
            Span<char> buffer = stackalloc char[prefixLength + 68];
            Span<char> prefixBuffer = buffer.Slice(0, prefixLength);
            Span<char> idBuffer = buffer.Slice(prefixLength);
            
            ReadOnlySpan<char> prefixSpan = Prefix.AsSpan();
            charsWritten = 0;
            if (!Prefix.TryCopyTo(prefixBuffer))
            {
                return false;
            }

            charsWritten = Prefix.Length;
            if (!_id.TryFormat(idBuffer, out int idWritten, format))
            {
                return false;
            }

            charsWritten += idWritten;
            buffer = buffer.Slice(0, charsWritten);
            
            return buffer.TryCopyTo(destination);
        }

        public bool Equals(CommandSequenceId other) { return _id == other._id; }

        public override bool Equals(object other)
        {
            if ((other == null) || !(other is CommandSequenceId)) 
            {
                return false;
            }

            return this.Equals((CommandSequenceId)other);
        }

        public override int GetHashCode() { return _id.GetHashCode(); }

        public static bool operator ==(CommandSequenceId a, CommandSequenceId b) { return a._id == b._id; }
        public static bool operator !=(CommandSequenceId a, CommandSequenceId b) { return a._id != b._id; }
    }
}
