// <auto-generated />
using System;
using EventSourcing.Net.Abstractions.Contracts;

namespace EventSourcing.Net.Abstractions.Identities
{
    /// <summary>
    /// Id of mapping for type.
    /// </summary>
    /// <remarks>Generated from EventSourcing.CodeGeneration.Identities.tt</remarks>
    public readonly struct TypeMappingId : IIdentity, IEquatable<TypeMappingId>
    {
        private readonly Guid _id;

        /// <summary>
        /// Get the prefix.
        /// </summary>
        public static readonly string Prefix = "type-mapping_";

        /// <summary>
        /// Get empty TypeMappingId.
        /// </summary>
        public static readonly TypeMappingId Empty = new TypeMappingId(Guid.Empty);

        /// <summary>
        /// Create TypeMappingId with random value.
        /// </summary>
        public static TypeMappingId New()
        {
            return new TypeMappingId(Guid.NewGuid());
        }

        /// <summary>
        /// Initiate new object.
        /// </summary>
        public TypeMappingId(Guid id)
        {
            _id = id;
        }

        /// <summary>
        /// Parse from string.
        /// </summary>
        /// <param name="serializedId">String value.</param>
        /// <returns>Id of mapping for type.</returns>
        /// <exception cref="ArgumentException">String cannot be parsed to TypeMappingId.</exception>
        public static TypeMappingId Parse(string serializedId)
        {
            if (!serializedId.StartsWith(Prefix, StringComparison.Ordinal))
            {
                throw new ArgumentException("Invalid TypeMappingId", "serializedId");
            }

            ReadOnlySpan<char> span = serializedId.AsSpan();
            Guid id = Guid.Parse(span.Slice(Prefix.Length));

            return new TypeMappingId(id);
        }

        /// <summary>
        /// Parse from string without throwing exception.
        /// </summary>
        /// <param name="serializedId">String value.</param>
        /// <param name="id">Parsed TypeMappingId.</param>
        /// <returns>True if parsed successfully, otherwise false.</returns>
        public static bool TryParse(string serializedId, out TypeMappingId id)
        {
            Guid guid;

            if (!string.IsNullOrWhiteSpace(serializedId) && serializedId.StartsWith(Prefix, StringComparison.Ordinal))
            {
                ReadOnlySpan<char> span = serializedId.AsSpan().Slice(Prefix.Length);
                if (Guid.TryParse(span, out guid))
                {
                    id = new TypeMappingId(guid);
                    return true;
                }
            }

            id = default(TypeMappingId);
            return false;
        }

        /// <summary>
        /// Get internal id.
        /// </summary>
        public Guid Id => _id;

        public static implicit operator Guid(TypeMappingId id)
        {
            return id._id;
        }

        public static implicit operator TypeMappingId(Guid id)
        {
            return new TypeMappingId(id);
        }

        public override string ToString()
        {
            return string.Concat(Prefix, _id.ToString());
        }

        public bool Equals(TypeMappingId other) { return _id == other._id; }

        public override bool Equals(object other)
        {
            if ((other == null) || !(other is TypeMappingId)) 
            {
                return false;
            }

            return this.Equals((TypeMappingId)other);
        }

        public override int GetHashCode() { return _id.GetHashCode(); }

        public static bool operator ==(TypeMappingId a, TypeMappingId b) { return a._id == b._id; }
        public static bool operator !=(TypeMappingId a, TypeMappingId b) { return a._id != b._id; }
    }
}

