// <auto-generated />
using System;
using EventSourcing.Abstractions.Contracts;

namespace EventSourcing.Abstractions.Identities
{
    /// <summary>
    /// Tenant identifier.
    /// </summary>
    /// <remarks>Generated from EventSourcing.CodeGeneration.Identities.tt</remarks>
    public readonly partial struct TenantId : IIdentity, IEquatable<TenantId>
    {
        private readonly Guid _id;

        /// <summary>
        /// Get the prefix.
        /// </summary>
        public static readonly string Prefix = "tenant_";

        /// <summary>
        /// Get empty TenantId.
        /// </summary>
        public static readonly TenantId Empty = new TenantId(Guid.Empty);

        /// <summary>
        /// Create TenantId with random value.
        /// </summary>
        public static TenantId New()
        {
            return new TenantId(Guid.NewGuid());
        }

        /// <summary>
        /// Initiate new object.
        /// </summary>
        public TenantId(Guid id)
        {
            _id = id;
        }

        /// <summary>
        /// Parse from string.
        /// </summary>
        /// <param name="serializedId">String value.</param>
        /// <returns>Tenant identifier.</returns>
        /// <exception cref="ArgumentException">String cannot be parsed to TenantId.</exception>
        public static TenantId Parse(string serializedId)
        {
            if (!serializedId.StartsWith(Prefix, StringComparison.Ordinal))
            {
                throw new ArgumentException("Invalid TenantId", "serializedId");
            }

            ReadOnlySpan<char> span = serializedId.AsSpan();
            Guid id = Guid.Parse(span.Slice(Prefix.Length));

            return new TenantId(id);
        }

        /// <summary>
        /// Parse from string without throwing exception.
        /// </summary>
        /// <param name="serializedId">String value.</param>
        /// <param name="id">Parsed TenantId.</param>
        /// <returns>True if parsed successfully, otherwise false.</returns>
        public static bool TryParse(string serializedId, out TenantId id)
        {
            Guid guid;

            if (!string.IsNullOrWhiteSpace(serializedId) && serializedId.StartsWith(Prefix, StringComparison.Ordinal))
            {
                ReadOnlySpan<char> span = serializedId.AsSpan().Slice(Prefix.Length);
                if (Guid.TryParse(span, out guid))
                {
                    id = new TenantId(guid);
                    return true;
                }
            }

            id = default(TenantId);
            return false;
        }

        /// <summary>
        /// Get internal id.
        /// </summary>
        public Guid Id => _id;

        public static implicit operator Guid(TenantId id)
        {
            return id._id;
        }

        public static implicit operator TenantId(Guid id)
        {
            return new TenantId(id);
        }

        public override string ToString()
        {
            return string.Concat(Prefix, _id.ToString());
        }

        public bool Equals(TenantId other) { return _id == other._id; }

        public override bool Equals(object other)
        {
            if ((other == null) || !(other is TenantId)) 
            {
                return false;
            }

            return this.Equals((TenantId)other);
        }

        public override int GetHashCode() { return _id.GetHashCode(); }

        public static bool operator ==(TenantId a, TenantId b) { return a._id == b._id; }
        public static bool operator !=(TenantId a, TenantId b) { return a._id != b._id; }
    }
}

